### ISSUE TITLE
Failed to load resource error

### ISSUE THREAD

**Issue by garybelvin** [steveoni/Face-rec#3]
I just downloaded your example code, unzipped the file, put it on my local webserver in a directory called "face" and it is currently generating this error (screenshot attached).

I can't figure out what I'm doing wrong here, any help at all would be greatly appreciated.
![Capture](https://user-images.githubusercontent.com/801493/97332703-22c9cc00-1851-11eb-9a24-646fc48fc3d9.PNG)

**Comment by steveoni** [comment]
is not ment to even show error, since the file it is looking for is in `models/`.

Cross check the directory `models/` to see if the file is actually there

**Comment by garybelvin** [comment]
The file does exist. It is trying to access it as if the files were in the root directory of the web server, but they aren't.  They are in a directory named "face".

What it is trying to access...
http://localhost/models/ssd_mobilenetv1_model-weights_manifest.json

What it should be accessing
http://localhost/face/models/ssd_mobilenetv1_model-weights_manifest.json

I changed the URL code in the index file but it didn't have an impact.

const MODEL_URL = '/models'

I changed it to 

const MODEL_URL = '/face/models'

**Comment by steveoni** [comment]
try running the server from the directory `face/`

**Comment by garybelvin** [comment]
It works, I'm really sorry.  I didn't realize it takes 10ish seconds to render the page in its entirety.
